# Generated by Django 2.0 on 2017-12-20 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='meta_order',
            field=models.SmallIntegerField(default=None, null=True),
        ),
    ]
