# Generated by Django 2.0 on 2017-12-20 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0002_puzzle_meta_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puzzle',
            old_name='template',
            new_name='short_name',
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='meta_order',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
