# Generated by Django 2.0 on 2017-12-20 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0003_auto_20171219_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='metapuzzle',
            name='description',
            field=models.TextField(default='What technology should I use to build my spoooooky website?  Originally written for Coding Dojo students in October 2017.'),
            preserve_default=False,
        ),
    ]
