# Generated by Django 2.0 on 2018-02-01 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0005_puzzleanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzleanswer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puzzle_answers', to=settings.AUTH_USER_MODEL),
        ),
    ]
