# Generated by Django 2.0 on 2018-02-02 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0007_metaanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metaanswer',
            name='puzzle',
        ),
        migrations.RemoveField(
            model_name='metaanswer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='puzzle',
            name='metapuzzle',
        ),
        migrations.AddField(
            model_name='puzzle',
            name='metapuzzles',
            field=models.ManyToManyField(related_name='_puzzle_metapuzzles_+', to='puzzles.Puzzle'),
        ),
        migrations.DeleteModel(
            name='MetaAnswer',
        ),
        migrations.DeleteModel(
            name='Metapuzzle',
        ),
    ]
