# Generated by Django 2.0 on 2018-02-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0008_auto_20180201_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
