# Generated by Django 2.0 on 2018-02-02 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0009_puzzle_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='metapuzzles',
            field=models.ManyToManyField(blank=True, related_name='_puzzle_metapuzzles_+', to='puzzles.Puzzle'),
        ),
    ]
