# Generated by Django 2.0 on 2018-02-28 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0012_puzzle_show_on_main_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuzzleSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('folder', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='puzzle',
            name='description',
        ),
        migrations.RemoveField(
            model_name='puzzle',
            name='show_on_main_page',
        ),
        migrations.AddField(
            model_name='puzzle',
            name='puzzle_set',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='puzzles', to='puzzles.PuzzleSet'),
            preserve_default=False,
        ),
    ]
